(() => {
const $=id=>document.getElementById(id);
const packs={
 social:["Most likely to accidentally become famous","Best person to bring to a terrible party","Most likely to survive a reality show","Most likely to reply instantly at 3am","Most trustworthy with a secret","Most likely to start an argument with a stranger","Best person to have as a neighbour","Most likely to disappear from the group chat for a month"],
 life:["Most likely to retire early","Most likely to move countries on a whim","Most likely to spend £10,000 in one weekend","Most likely to own a ridiculous pet","Most likely to become a regular at the same pub","Most likely to miss a flight","Most likely to end up living in the countryside","Most likely to accidentally join a cult"],
 nerdy:["Most likely to open a spreadsheet for this","Most likely to say 'technically…'","Most likely to run a simulation instead of guessing","Most likely to read the methods section first","Most likely to become Reviewer 2","Most likely to automate a five-minute task","Most likely to own too many monitors","Most likely to turn a hobby into a research project"]
};packs.mixed=[...packs.social,...packs.life,...packs.nerdy];
let s={players:[],prompt:"",voter:0,rankings:[],chosen:[],used:[]};
function parse(v){return [...new Set(v.split(/[,\n]/).map(x=>x.trim()).filter(Boolean))]}
function show(id){["setup","pass","vote","results"].forEach(x=>$(x).classList.toggle("hidden",x!==id))}
function pickPrompt(){let pool=packs[pack.value]||packs.mixed, avail=pool.filter(x=>!s.used.includes(x));if(!avail.length){s.used=[];avail=pool}s.prompt=avail[Math.floor(Math.random()*avail.length)];s.used.push(s.prompt)}
function beginPrompt(){pickPrompt();s.voter=0;s.rankings=[];passToVoter()}
function passToVoter(){show("pass");roundLabel.textContent=`Prompt ${s.used.length}`;title.textContent=s.prompt;progress.textContent=`${s.voter+1}/${s.players.length}`;passName.textContent=s.players[s.voter]}
function renderVote(){show("vote");$("prompt").textContent=s.prompt;s.chosen=[];drawRank()}
function drawRank(){chosen.innerHTML=s.chosen.map((name,i)=>`<button class="rank-item" data-undo="${name}"><span class="rank-num">${i+1}</span><strong>${name}</strong></button>`).join("");choices.innerHTML=s.players.filter(x=>!s.chosen.includes(x)).map(name=>`<button class="option" data-pick="${name}">${name}</button>`).join("");submit.disabled=s.chosen.length!==s.players.length;document.querySelectorAll("[data-pick]").forEach(b=>b.onclick=()=>{s.chosen.push(b.dataset.pick);drawRank()});document.querySelectorAll("[data-undo]").forEach(b=>b.onclick=()=>{s.chosen=s.chosen.slice(0,s.chosen.indexOf(b.dataset.undo));drawRank()})}
function submitRank(){s.rankings.push([...s.chosen]);s.voter++;if(s.voter<s.players.length)passToVoter();else reveal()}
function reveal(){show("results");resultPrompt.textContent=s.prompt;let stats=s.players.map(name=>{let vals=s.rankings.map(r=>r.indexOf(name)+1),avg=vals.reduce((a,b)=>a+b,0)/vals.length,variance=vals.reduce((a,b)=>a+(b-avg)**2,0)/vals.length;return{name,avg,sd:Math.sqrt(variance),vals}}).sort((a,b)=>a.avg-b.avg);ranking.innerHTML=stats.map((x,i)=>`<div class="rank-item"><span class="rank-num">${i+1}</span><div style="flex:1"><strong>${x.name}</strong><div class="muted">average rank ${x.avg.toFixed(2)}</div><div class="bar"><span style="width:${100-(x.avg-1)/(s.players.length-1||1)*85}%"></span></div></div></div>`).join("");let d=[...stats].sort((a,b)=>b.sd-a.sd)[0];disputed.textContent=`${d.name} split the room most (rank standard deviation ${d.sd.toFixed(2)}).`;progress.textContent="Reveal"}
start.onclick=()=>{s.players=parse(players.value);if(s.players.length<3){$("status").textContent="Add at least 3 players.";return}$("status").textContent="";beginPrompt()};ready.onclick=renderVote;submit.onclick=submitRank;next.onclick=beginPrompt;resetBtn.onclick=()=>{if(confirm("Reset Rank the Room?"))location.reload()};rulesBtn.onclick=()=>{rulesContent.innerHTML="<p class=eyebrow>How to play</p><h2>Rank privately, reveal together</h2><p class=muted>For each prompt, every player privately ranks everyone from most to least. The game averages those positions to create the room's consensus and also shows who produced the most disagreement.</p>";rulesModal.showModal()};document.querySelector("[data-close]").onclick=()=>rulesModal.close();
})();