(() => {
const $=id=>document.getElementById(id);
const words={
 food:["ramen","tiramisu","avocado","croissant","kimchi","lasagna","sushi","popcorn","pancake","curry","bagel","mozzarella"],
 places:["airport","museum","supermarket","laboratory","beach","library","hospital","nightclub","castle","train station","university","zoo"],
 objects:["umbrella","toothbrush","microscope","passport","headphones","ladder","kettle","suitcase","keyboard","bicycle","candle","camera"],
 science:["ribosome","protein","gravity","neuron","bacteria","telescope","DNA","laser","enzyme","volcano","atom","fossil"]
};words.mixed=[...words.food,...words.places,...words.objects,...words.science];
let s={players:[],scores:{},impostor:0,word:"",viewer:0,voter:0,votes:[],round:0};
function parse(v){return [...new Set(v.split(/[,\n]/).map(x=>x.trim()).filter(Boolean))]}
function show(id){["setup","pass","roleView","clueView","votePass","voteView","impostorGuess","results"].forEach(x=>$(x).classList.toggle("hidden",x!==id))}
function score(){scoreboard.innerHTML=s.players.map(p=>`<span class="scorechip">${p} <strong>${s.scores[p]||0}</strong></span>`).join("")}
function newRound(){s.round++;s.impostor=Math.floor(Math.random()*s.players.length);let pool=words[category.value]||words.mixed;s.word=pool[Math.floor(Math.random()*pool.length)];s.viewer=0;s.voter=0;s.votes=[];roundLabel.textContent=`Round ${s.round}`;phase.textContent="Learn your roles";passRole()}
function passRole(){show("pass");passName.textContent=s.players[s.viewer]}
function revealRole(){show("roleView");let imp=s.viewer===s.impostor;roleLabel.textContent=imp?"You are":"Secret word";roleWord.textContent=imp?"THE IMPOSTOR":s.word;roleHint.textContent=imp?"Listen carefully. Blend in, then survive the vote.":"Give a clue that proves you know it without making the answer obvious."}
function hideRoleNext(){s.viewer++;if(s.viewer<s.players.length)passRole();else{show("clueView");phase.textContent="Clues";let order=[...s.players.slice(s.impostor+1),...s.players.slice(0,s.impostor+1)];clueOrder.textContent=`Suggested order: ${order.join(" → ")}`}}
function votePassFn(){show("votePass");phase.textContent="Voting";voterName.textContent=s.players[s.voter]}
function voteScreen(){show("voteView");let voter=s.players[s.voter];voteOptions.innerHTML=s.players.filter(p=>p!==voter).map(p=>`<button class="option" data-vote="${p}">${p}</button>`).join("");document.querySelectorAll("[data-vote]").forEach(b=>b.onclick=()=>cast(b.dataset.vote))}
function cast(name){s.votes.push({voter:s.players[s.voter],target:name});s.voter++;if(s.voter<s.players.length)votePassFn();else resolveVotes()}
function resolveVotes(){let counts={};s.votes.forEach(v=>counts[v.target]=(counts[v.target]||0)+1);let max=Math.max(...Object.values(counts)),leaders=Object.keys(counts).filter(k=>counts[k]===max),imp=s.players[s.impostor],caught=leaders.length===1&&leaders[0]===imp;s._counts=counts;s._caught=caught;if(caught){caughtName.textContent=imp;show("impostorGuess")}else{for(let p of s.players)if(p===imp)s.scores[p]=(s.scores[p]||0)+2;finish(false,false)}}
function finish(caught,guessed){let imp=s.players[s.impostor];if(caught){s.players.filter(p=>p!==imp).forEach(p=>s.scores[p]=(s.scores[p]||0)+1);if(guessed)s.scores[imp]=(s.scores[imp]||0)+1}show("results");phase.textContent="Reveal";resultTitle.textContent=caught?(guessed?"Caught — but escaped with the word":"Impostor caught"):"Impostor survives";resultSub.textContent=`${imp} was the impostor. The word was “${s.word}”.`;let entries=s.players.map(p=>({p,n:s._counts[p]||0})).sort((a,b)=>b.n-a.n);tally.innerHTML=entries.map(x=>`<div class="rank-item"><span class="rank-num">${x.n}</span><strong>${x.p}</strong><span class="muted">vote${x.n===1?"":"s"}</span></div>`).join("");score()}
start.onclick=()=>{s.players=parse(players.value);if(s.players.length<4){$("status").textContent="Add at least 4 players.";return}s.scores=Object.fromEntries(s.players.map(p=>[p,0]));$("status").textContent="";score();newRound()};reveal.onclick=revealRole;hideRole.onclick=hideRoleNext;beginVoting.onclick=votePassFn;voteReady.onclick=voteScreen;submitGuess.onclick=()=>{let guessed=wordGuess.value.trim().toLowerCase()===s.word.toLowerCase();finish(true,guessed);wordGuess.value=""};nextRound.onclick=newRound;resetBtn.onclick=()=>{if(confirm("Reset Impostor Word?"))location.reload()};rulesBtn.onclick=()=>{rulesContent.innerHTML="<p class=eyebrow>How to play</p><h2>Prove you know the word</h2><p class=muted>Everyone except one impostor sees the same secret word. Go around giving one clue each. Then vote privately. If the impostor survives the vote they score 2; if caught, the others score 1 each, but the impostor can steal 1 point by guessing the word.</p>";rulesModal.showModal()};document.querySelector("[data-close]").onclick=()=>rulesModal.close();
})();