(() => {
const $=id=>document.getElementById(id);
const qs=[
 {q:"What is a group of flamingos called?",a:"A flamboyance",e:"The collective noun commonly used for flamingos is a flamboyance."},
 {q:"What is the dot above a lowercase i or j called?",a:"A tittle",e:"That tiny dot has its own typographic name: tittle."},
 {q:"Which animal has fingerprints so similar to humans that they can confuse investigators?",a:"Koalas",e:"Koala fingerprints have loops and whorls strikingly similar to ours."},
 {q:"What is the only mammal capable of true sustained flight?",a:"A bat",e:"Flying squirrels glide; bats generate powered, sustained flight."},
 {q:"What food was the first to be deliberately eaten in space by an American astronaut?",a:"Applesauce",e:"John Glenn ate tubed applesauce during Friendship 7 in 1962."},
 {q:"What is Scotland's national animal?",a:"The unicorn",e:"The unicorn has been a Scottish heraldic symbol for centuries."},
 {q:"What is the technical name for the fear of long words?",a:"Hippopotomonstrosesquipedaliophobia",e:"The intentionally intimidating term is itself extremely long."},
 {q:"What common fruit floats in water because roughly a quarter of its volume is air?",a:"An apple",e:"Air pockets in apple tissue make many apples buoyant."},
 {q:"What is the largest organ of the human body?",a:"The skin",e:"By surface area and mass, skin is the body's largest organ."},
 {q:"Which planet has the shortest day in the Solar System?",a:"Jupiter",e:"Jupiter rotates in roughly ten hours."},
 {q:"What is the name for the smell produced when rain falls on dry ground?",a:"Petrichor",e:"Petrichor describes the earthy smell associated with rain on dry soil."},
 {q:"Which bird can fly backwards under its own power?",a:"A hummingbird",e:"Hummingbirds can reverse the direction of lift generated by their wings."},
 {q:"What colour is an aircraft's so-called black box usually painted?",a:"Bright orange",e:"Flight recorders are conspicuously coloured to help recovery teams find them."},
 {q:"Which metal is liquid at ordinary room temperature?",a:"Mercury",e:"Mercury's melting point is about −39 °C."},
 {q:"What is the name of the plastic tip at the end of a shoelace?",a:"An aglet",e:"The small sheath that prevents fraying is called an aglet."},
 {q:"What gas makes up most of Earth's atmosphere?",a:"Nitrogen",e:"Earth's dry atmosphere is about 78% nitrogen."},
 {q:"What animal's heart is located in its head region?",a:"A shrimp",e:"A shrimp's heart sits in the cephalothorax, the fused head-and-thorax region."},
 {q:"Which continent is the driest overall?",a:"Antarctica",e:"Despite its ice, Antarctica receives so little precipitation that it is a polar desert."},
 {q:"What is the smallest bone in the human body?",a:"The stapes",e:"The stapes is a tiny middle-ear bone."},
 {q:"What is a baby rabbit called?",a:"A kit",e:"Young rabbits are called kits or kittens."}
];
let s={players:[],scores:{},round:0,total:7,deck:[],question:null,idx:0,bluffs:[],votes:[],voteIdx:0,options:[]};
function parse(v){return [...new Set(v.split(/[,\n]/).map(x=>x.trim()).filter(Boolean))]}
function shuffle(a){a=[...a];for(let i=a.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function show(id){["setup","questionView","pass","bluffView","voteView","results","gameOver"].forEach(x=>$(x).classList.toggle("hidden",x!==id))}
function score(){scores.innerHTML=s.players.map(p=>`<span class="scorechip">${p} <strong>${s.scores[p]||0}</strong></span>`).join("")}
function newQuestion(){if(s.round>=s.total||!s.deck.length){finishGame();return}s.question=s.deck.shift();s.round++;s.idx=0;s.bluffs=[];s.votes=[];s.voteIdx=0;roundLabel.textContent=`Round ${s.round} / ${s.total}`;phase.textContent="Question";question.textContent=s.question.q;show("questionView")}
function bluffPass(){show("pass");passLabel.textContent="Write a bluff";passName.textContent=s.players[s.idx];passHint.textContent="Make it plausible enough that someone might choose it."}
function bluffReady(){show("bluffView");bluffQuestion.textContent=s.question.q;bluffInput.value="";bluffStatus.textContent="";bluffInput.focus()}
function submitBluffFn(){let v=bluffInput.value.trim();if(!v)return;if(v.toLowerCase()===s.question.a.toLowerCase()){bluffStatus.textContent="Too accurate — write a wrong answer.";return}if(s.bluffs.some(x=>x.text.toLowerCase()===v.toLowerCase())){bluffStatus.textContent="Someone already submitted that answer. Try another.";return}s.bluffs.push({player:s.players[s.idx],text:v});s.idx++;if(s.idx<s.players.length)bluffPass();else beginVotes()}
function beginVotes(){s.options=shuffle([{player:null,text:s.question.a,truth:true},...s.bluffs.map(x=>({...x,truth:false}))]);s.voteIdx=0;votePass()}
function votePass(){show("pass");passLabel.textContent="Choose the truth";passName.textContent=s.players[s.voteIdx];passHint.textContent="Don't choose your own bluff."}
function voteReady(){show("voteView");voteQuestion.textContent=s.question.q;let voter=s.players[s.voteIdx];answers.innerHTML=s.options.map((o,i)=>`<button class="option ${o.player===voter?"mine":""}" ${o.player===voter?"disabled":""} data-answer="${i}">${escapeHtml(o.text)}</button>`).join("");document.querySelectorAll("[data-answer]").forEach(b=>b.onclick=()=>cast(+b.dataset.answer))}
function cast(i){let o=s.options[i],voter=s.players[s.voteIdx];s.votes.push({voter,choice:i});if(o.truth)s.scores[voter]+=2;else if(o.player)s.scores[o.player]+=1;s.voteIdx++;if(s.voteIdx<s.players.length)votePass();else reveal()}
function reveal(){show("results");phase.textContent="Reveal";truth.textContent=s.question.a;explanation.textContent=s.question.e;resultRows.innerHTML=s.options.map((o,i)=>{let voters=s.votes.filter(v=>v.choice===i).map(v=>v.voter);return`<div class="answer ${o.truth?"truth":""}"><div class="row between"><strong>${escapeHtml(o.text)}</strong><span class="badge">${o.truth?"TRUTH":escapeHtml(o.player)}</span></div><p class="muted" style="margin:8px 0 0">${voters.length?voters.join(", ")+" chose this":"Nobody chose this"}</p></div>`}).join("");score()}
function finishGame(){show("gameOver");let max=Math.max(...Object.values(s.scores)),leaders=s.players.filter(p=>s.scores[p]===max);winner.textContent=leaders.length>1?"Tie game":`${leaders[0]} wins`;final.textContent=s.players.map(p=>`${p} ${s.scores[p]}`).join(" · ")}
function escapeHtml(v){return String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
start.onclick=()=>{s.players=parse(players.value);if(s.players.length<3){$("status").textContent="Add at least 3 players.";return}s.total=Math.max(1,Math.min(+rounds.value||7,qs.length));s.scores=Object.fromEntries(s.players.map(p=>[p,0]));s.deck=shuffle(qs);s.round=0;$("status").textContent="";score();newQuestion()};beginBluffs.onclick=bluffPass;ready.onclick=()=>passLabel.textContent==="Write a bluff"?bluffReady():voteReady();submitBluff.onclick=submitBluffFn;next.onclick=newQuestion;again.onclick=()=>location.reload();resetBtn.onclick=()=>{if(confirm("Reset Bluff Box?"))location.reload()};rulesBtn.onclick=()=>{rulesContent.innerHTML="<p class=eyebrow>How to play</p><h2>Write lies people want to believe</h2><p class=muted>Everyone privately invents a plausible wrong answer. The real answer is shuffled in with the bluffs. You score 2 for choosing the truth and 1 every time another player chooses your bluff.</p>";rulesModal.showModal()};document.querySelector("[data-close]").onclick=()=>rulesModal.close();
})();